experiment_name: nh_AORC_hourly
seed: 101
train_basin_file: /Users/jmframe/CAMELS_data_sample/valid_basins.txt
validation_basin_file: /Users/jmframe/CAMELS_data_sample/valid_basins.txt
test_basin_file: /Users/jmframe/CAMELS_data_sample/test_basins.txt
train_start_date: "01/10/1998"
train_end_date: "01/12/1998"
validation_start_date: "01/10/1998"
validation_end_date: "01/12/1998"
test_start_date: "01/10/1998"
test_end_date: "01/12/1998"
clip_gradient_norm: 1
sequence_length: 256
device: mps
epochs: 5
hidden_size: 256
learning_rate: 0.0001
batch_sites: 2
epoch_coverage_factor: 1
batch_timesteps: 256
variogram_weight: 1
fdc_weight: 1
residual_weight: 1
residual_loss: "mse"
output_dir: ./runs
#dataset: hourly_camels_us
data_dir: /Users/jmframe/CAMELS_data_sample/
forcings: aorc_hourly
dynamic_inputs:
- APCP_surface
- TMP_2maboveground
static_attributes:
  - elev_mean
  - slope_mean
target_variables:
  - QObs(mm/h)
